---

- name: install and start PHP and apache
  hosts: app
  remote_user: clement
  become: true

  roles:
    - apache
    - php

- name: install and start mariaDB
  hosts: db
  remote_user: clement
  become: true

  roles:
    - mariaDB
